import path from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

// ESLint 9 flat configuration. The Next.js shareable config still ships in
// eslintrc format, so FlatCompat translates it. The lint script runs the
// ESLint CLI directly because `next lint` is deprecated.
const compat = new FlatCompat({
  baseDirectory: path.dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "coverage/**",
      "test-results/**",
      "backend/**",
      "public/**",
      // Generated artifacts are excluded from lint; they are regenerated by
      // scripts and gated for freshness in CI.
      "lib/api/generated/**",
      "lib/guide/generated/**",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals"),
];

export default config;
