"""Seed plan sheet and CAD-aware metadata for the Brookside Meadows fixture.

Phase 6 seeds a synthetic civil plan sheet index, CAD-aware feature metadata,
and plan references that connect documents, sheets, and civil features. None of
this is parsed from a real CAD file. It is review-support metadata authored to
mirror the Brookside Meadows story, including the intentional gaps and conflicts
(for example the referenced but not included revised grading sheet C-3.1 and the
Basin A versus Basin 1 naming conflict).

Plan consistency findings are not seeded here. They are generated by the plan
consistency service from this seeded data so there is a single source of truth.
"""

from __future__ import annotations

from sqlalchemy.orm import Session

from app.db import models
from app.db.seed import PROJECT_ID


def _sheet(
    sheet_id: str,
    number: str,
    title: str,
    discipline: str,
    revision: str | None,
    revision_date: str | None,
    status: str,
    file_name: str | None,
    purpose: str,
    documents: list[str],
    checklist: list[str],
    findings: list[str],
) -> dict:
    return {
        "sheet_id": sheet_id,
        "project_id": PROJECT_ID,
        "sheet_number": number,
        "sheet_title": title,
        "discipline": discipline,
        "revision": revision,
        "revision_date": revision_date,
        "status": status,
        "file_name": file_name,
        "sheet_purpose": purpose,
        "related_documents": documents,
        "related_checklist_items": checklist,
        "related_findings": findings,
    }


PLAN_SHEETS: list[dict] = [
    _sheet(
        "sheet_c00", "C-0.0", "Cover Sheet", "cover", "0", "2026-05-15",
        "current", "C-0.0-cover.pdf",
        "Title sheet, sheet index, and general notes for the plan set.",
        ["doc_site_narrative"], [], [],
    ),
    _sheet(
        "sheet_c10", "C-1.0", "Existing Conditions Plan", "existing_conditions",
        "0", "2026-05-15", "current", "C-1.0-existing-conditions.pdf",
        "Pre-development topography, wood line, meadow, stream, wetland, and "
        "the Quarry Road culvert.",
        ["doc_existing_conditions"], ["chk_drainage_areas"], [],
    ),
    _sheet(
        "sheet_c20", "C-2.0", "Subdivision Layout Plan", "layout", "0",
        "2026-05-15", "current", "C-2.0-layout.pdf",
        "Lot layout, Brookside Drive, the loop road, and the Meadow Court "
        "cul-de-sac.",
        ["doc_layout_plan"], ["chk_drainage_areas"], [],
    ),
    _sheet(
        "sheet_c30", "C-3.0", "Grading and Drainage Plan", "grading", "1",
        "2026-05-20", "current", "C-3.0-grading-drainage.pdf",
        "Grading, storm drain network, and stormwater basin locations.",
        ["doc_grading_drainage"],
        ["chk_reference_consistency", "chk_drainage_areas"],
        ["find_basin_naming"],
    ),
    _sheet(
        "sheet_c31", "C-3.1", "Revised Grading and Drainage Plan", "grading",
        "2", "2026-06-05", "referenced_not_included", "C-3.1-grading-REV.pdf",
        "Revised grading sheet cited by the site plan narrative but not "
        "included in the submitted package.",
        ["doc_revised_c31", "doc_site_narrative"],
        ["chk_referenced_sheets_present"],
        ["find_missing_sheet"],
    ),
    _sheet(
        "sheet_c40", "C-4.0", "Utility Plan", "utility", "0", "2026-05-15",
        "current", "C-4.0-utility.pdf",
        "Water main, gravity sewer, sanitary pump station, and dry utilities.",
        ["doc_utility_plan"], ["chk_rfi_closure"], ["find_rfi_open"],
    ),
    _sheet(
        "sheet_c50", "C-5.0", "Erosion and Sediment Control Plan",
        "erosion_control", "0", "2026-05-15", "current", "C-5.0-escp.pdf",
        "Silt fence, inlet protection, construction entrance, and "
        "stabilization measures.",
        ["doc_escp"], ["chk_erosion_controls", "chk_escp_phasing"],
        ["find_escp_phasing"],
    ),
    _sheet(
        "sheet_c51", "C-5.1", "Construction Phasing and Erosion Control Details",
        "erosion_control", "0", "2026-05-15", "needs_reviewer_confirmation",
        "C-5.1-phasing-details.pdf",
        "Construction phasing sequence and erosion control details cited by the "
        "erosion control plan; sequence notes are incomplete or unclear.",
        ["doc_phasing_plan", "doc_escp"], ["chk_escp_phasing"],
        ["find_escp_phasing"],
    ),
    _sheet(
        "sheet_c60", "C-6.0", "Stormwater Management Details", "drainage", "0",
        "2026-05-15", "current", "C-6.0-swm-details.pdf",
        "Basin sections, outlet structures, and stormwater management details.",
        ["doc_stormwater_report"],
        ["chk_bmp_identified", "chk_outfall_identified"], [],
    ),
    _sheet(
        "sheet_c70", "C-7.0", "Roadway Profiles", "profiles", "0", "2026-05-15",
        "current", "C-7.0-profiles.pdf",
        "Centerline profiles for Brookside Drive and Meadow Court.",
        ["doc_grading_drainage"], [], [],
    ),
    _sheet(
        "sheet_c80", "C-8.0", "Landscape and Buffer Plan", "landscaping", "0",
        "2026-05-15", "current", "C-8.0-landscape-buffer.pdf",
        "Landscaping and the wetland buffer planting along the southeast "
        "boundary.",
        [], ["chk_outfall_identified"], [],
    ),
    _sheet(
        "sheet_d10", "D-1.0", "Construction Details", "details", "0",
        "2026-05-15", "current", "D-1.0-details.pdf",
        "Standard construction details for drainage structures and pavement.",
        ["doc_grading_drainage"], [], [],
    ),
]


def _cad(
    cad_id: str,
    sheet_id: str | None,
    source_type: str,
    entity_type: str,
    label: str,
    layer: str | None,
    discipline: str | None,
    document_id: str | None,
    checklist_item_id: str | None,
    finding_id: str | None,
    notes: str,
) -> dict:
    return {
        "cad_metadata_id": cad_id,
        "project_id": PROJECT_ID,
        "sheet_id": sheet_id,
        "source_type": source_type,
        "entity_type": entity_type,
        "entity_label": label,
        "layer_name": layer,
        "discipline": discipline,
        "related_document_id": document_id,
        "related_checklist_item_id": checklist_item_id,
        "related_finding_id": finding_id,
        "notes": notes,
    }


CAD_METADATA: list[dict] = [
    _cad(
        "cad_basin_a", "sheet_c30", "report_reference", "basin", "Basin A",
        "C-DRNG-BASIN", "grading", "doc_grading_drainage",
        "chk_reference_consistency", "find_basin_naming",
        "Grading and drainage plan labels the basin Basin A (also shown as "
        "Pond A).",
    ),
    _cad(
        "cad_basin_1", "sheet_c60", "report_reference", "basin", "Basin 1",
        "C-DRNG-BASIN", "drainage", "doc_stormwater_report",
        "chk_reference_consistency", "find_basin_naming",
        "Stormwater management report refers to the same basin as Basin 1.",
    ),
    _cad(
        "cad_meadow_infil", "sheet_c30", "sheet_index", "basin",
        "Meadow infiltration basin", "C-DRNG-BASIN", "drainage",
        "doc_stormwater_report", "chk_infiltration_testing",
        "find_infiltration_missing",
        "Infiltration basin (Basin 2) proposed in the meadow for volume "
        "reduction and recharge.",
    ),
    _cad(
        "cad_wet_detention", "sheet_c30", "sheet_index", "basin",
        "Wet detention basin", "C-DRNG-BASIN", "drainage", "doc_oem_plan",
        "chk_oem_owner", "find_oem_owner",
        "Wet detention basin in the southeast low area; long-term maintenance "
        "ownership is unclear.",
    ),
    _cad(
        "cad_brookside_dr", "sheet_c20", "sheet_index", "road",
        "Brookside Drive", "C-ROAD-CL", "layout", "doc_layout_plan",
        "chk_drainage_areas", None,
        "Primary subdivision road serving the upland lots.",
    ),
    _cad(
        "cad_meadow_ct", "sheet_c20", "plan_note", "road", "Meadow Court",
        "C-ROAD-CL", "layout", "doc_layout_plan", "chk_drainage_areas", None,
        "Cul-de-sac serving the lower lots near the buffer.",
    ),
    _cad(
        "cad_quarry_culvert", "sheet_c10", "sheet_index", "culvert",
        "Quarry Road culvert", "C-DRNG-CULV", "drainage",
        "doc_existing_conditions", "chk_downstream_capacity",
        "find_downstream_capacity",
        "Existing 36-inch culvert and downstream discharge point under Quarry "
        "Road.",
    ),
    _cad(
        "cad_outfall_1", "sheet_c30", "sheet_index", "outfall", "Outfall 1",
        "C-DRNG-OUTF", "drainage", "doc_inspection_notes",
        "chk_inspection_closeout", "find_inspection_open",
        "Basin outlet and outfall where an inspection note flagged sediment "
        "without a recorded corrective action.",
    ),
    _cad(
        "cad_pipe_p12", "sheet_c30", "plan_note", "pipe", "Pipe P-12",
        "C-DRNG-PIPE", "drainage", "doc_rfi_log", "chk_rfi_closure",
        "find_rfi_open",
        "Storm drain pipe segment named in an open RFI about pipe material.",
    ),
    _cad(
        "cad_cb_7", "sheet_c30", "plan_note", "catch_basin", "Catch basin CB-7",
        "C-DRNG-STRC", "drainage", "doc_grading_drainage", None, None,
        "Catch basin in the storm drain network on the grading sheet.",
    ),
    _cad(
        "cad_wetland_buffer", "sheet_c80", "sheet_index", "wetland_buffer",
        "Wetland buffer", "C-ENV-BUFF", "landscaping",
        "doc_existing_conditions", "chk_outfall_identified", None,
        "Delineated wetland and 100-ft town buffer along the southeast "
        "boundary.",
    ),
    _cad(
        "cad_constr_entrance", "sheet_c50", "sheet_index",
        "construction_entrance", "Construction entrance", "C-EROS-ENTR",
        "erosion_control", "doc_escp", "chk_erosion_controls", None,
        "Stabilized construction entrance off Quarry Road.",
    ),
    _cad(
        "cad_silt_fence", "sheet_c50", "plan_note", "erosion_control",
        "Silt fence", "C-EROS-SILT", "erosion_control", "doc_escp",
        "chk_erosion_controls", None,
        "Perimeter silt fence along the downhill limits of disturbance.",
    ),
    _cad(
        "cad_pump_station", "sheet_c40", "sheet_index", "utility",
        "Utility pump station", "C-UTIL-PUMP", "utility", "doc_utility_plan",
        "chk_rfi_closure", None,
        "Sanitary pump station serving the low lots.",
    ),
    _cad(
        "cad_lot_17", "sheet_c20", "sheet_index", "lot", "Lot 17",
        "C-PROP-LOT", "layout", "doc_layout_plan", "chk_drainage_areas", None,
        "Representative upland lot contributing new impervious runoff.",
    ),
    _cad(
        "cad_lot_33", "sheet_c20", "sheet_index", "lot", "Lot 33",
        "C-PROP-LOT", "layout", "doc_layout_plan", "chk_groundwater_separation",
        None,
        "Representative lower lot near the buffer and shallow groundwater "
        "area.",
    ),
]


def _ref(
    ref_id: str,
    source_type: str,
    source_id: str,
    target_type: str,
    target_id: str,
    label: str,
    context: str,
    status: str,
    note: str,
) -> dict:
    return {
        "plan_reference_id": ref_id,
        "project_id": PROJECT_ID,
        "source_type": source_type,
        "source_id": source_id,
        "target_type": target_type,
        "target_id": target_id,
        "reference_label": label,
        "reference_context": context,
        "consistency_status": status,
        "review_note": note,
    }


PLAN_REFERENCES: list[dict] = [
    _ref(
        "pref_swr_c30", "document", "doc_stormwater_report", "plan_sheet",
        "sheet_c30", "Stormwater report references Grading and Drainage Plan "
        "C-3.0",
        "The stormwater management report cites the grading and drainage plan "
        "for basin locations.",
        "consistent",
        "Reference resolves to an included plan sheet.",
    ),
    _ref(
        "pref_swr_c31", "document", "doc_stormwater_report", "plan_sheet",
        "sheet_c31", "Narrative references revised Grading and Drainage Plan "
        "C-3.1",
        "The site plan narrative and report cite revised sheet C-3.1, which is "
        "not in the submitted package.",
        "missing_target",
        "Referenced revised sheet C-3.1 is not included in the package.",
    ),
    _ref(
        "pref_calc_basin_a", "document", "doc_hydrology_calcs", "cad_feature",
        "cad_basin_a", "Drainage calculations reference Basin A",
        "The drainage calculations refer to the basin as Basin A.",
        "conflicting_label",
        "Basin is called Basin A in the calculations but Basin 1 in the "
        "report.",
    ),
    _ref(
        "pref_grading_basin_1", "plan_sheet", "sheet_c60", "cad_feature",
        "cad_basin_1", "Stormwater details reference Basin 1",
        "The stormwater details sheet and report refer to the basin as Basin "
        "1.",
        "conflicting_label",
        "Basin is called Basin 1 in the report but Basin A on the grading "
        "plan.",
    ),
    _ref(
        "pref_oem_wet", "document", "doc_oem_plan", "cad_feature",
        "cad_wet_detention", "O&M plan references wet detention basin "
        "maintenance",
        "The operation and maintenance plan references wet detention basin "
        "maintenance.",
        "needs_human_review",
        "Plan sheet ownership notes for the wet detention basin maintenance "
        "party are unclear.",
    ),
    _ref(
        "pref_escp_entrance", "document", "doc_escp", "cad_feature",
        "cad_constr_entrance", "Erosion control plan references construction "
        "entrance",
        "The erosion and sediment control plan shows the construction "
        "entrance.",
        "consistent",
        "Construction entrance is shown on the erosion control plan.",
    ),
    _ref(
        "pref_inspect_outfall", "document", "doc_inspection_notes",
        "cad_feature", "cad_outfall_1", "Inspection note references Outfall 1",
        "An inspection note flags sediment at Outfall 1.",
        "needs_human_review",
        "Corrective action for the Outfall 1 deficiency is not shown on a "
        "current plan sheet.",
    ),
    _ref(
        "pref_rfi_pipe", "document", "doc_rfi_log", "cad_feature",
        "cad_pipe_p12", "RFI log references Pipe P-12",
        "An RFI asks about the material for Pipe P-12.",
        "missing_target",
        "The pipe material response for Pipe P-12 is missing from the RFI "
        "log.",
    ),
    _ref(
        "pref_util_pump", "document", "doc_utility_plan", "cad_feature",
        "cad_pump_station", "Utility plan references pump station",
        "The utility plan shows the sanitary pump station.",
        "consistent",
        "Pump station is shown on the utility plan.",
    ),
    _ref(
        "pref_layout_meadowct", "document", "doc_layout_plan", "cad_feature",
        "cad_meadow_ct", "Layout plan references Meadow Court",
        "The layout plan shows the Meadow Court cul-de-sac.",
        "consistent",
        "Meadow Court is shown on the layout plan.",
    ),
    _ref(
        "pref_escp_c51", "document", "doc_escp", "plan_sheet", "sheet_c51",
        "Erosion control phasing references Sheet C-5.1",
        "The erosion control plan ties phasing to construction phasing details "
        "on Sheet C-5.1.",
        "unclear",
        "Construction sequence notes on Sheet C-5.1 are incomplete or unclear.",
    ),
]


def plan_data_is_loaded(db: Session) -> bool:
    """Return True if plan sheets are already present for the project."""

    return (
        db.query(models.PlanSheet)
        .filter(models.PlanSheet.project_id == PROJECT_ID)
        .first()
        is not None
    )


def seed_plan_sheets(db: Session, *, force: bool = False) -> None:
    """Load the seeded plan sheets, CAD metadata, and plan references.

    Idempotent: if plan sheets already exist and force is False, seeding is
    skipped. Plan consistency findings are generated by the plan consistency
    service, not seeded here.
    """

    if plan_data_is_loaded(db):
        if not force:
            return
        for model in (
            models.PlanConsistencyFinding,
            models.PlanReference,
            models.CADMetadata,
            models.PlanSheet,
        ):
            db.query(model).filter(model.project_id == PROJECT_ID).delete()
        db.commit()

    db.add_all(models.PlanSheet(**sheet) for sheet in PLAN_SHEETS)
    db.add_all(models.CADMetadata(**record) for record in CAD_METADATA)
    db.add_all(models.PlanReference(**ref) for ref in PLAN_REFERENCES)
    db.commit()
