// Single source of truth for the Brookside Meadows conceptual aerial visual.
//
// Every surface that shows the Brookside aerial (Start Here, Proof of Concept,
// Guided Demo, Projects, and the social preview metadata) reads from this
// module, so the path, dimensions, alt text, and disclosure copy can never
// drift between placements. The dimensions are verified against the committed
// files by scripts/verify-brookside-media.mjs.
//
// Brookside Meadows is a synthetic public demo fixture. The visual is a
// conceptual rendering and must never be described as a real development,
// survey, or approved design.

export const brooksideMedia = {
  // Original conceptual aerial. Committed at public/images/civil-engineer and
  // never modified; derivatives are generated from it by script.
  image: {
    src: "/images/civil-engineer/brookside-project-thumbnail.webp",
    width: 1672,
    height: 941,
    alt: "Conceptual aerial visualization of the synthetic Brookside Meadows residential subdivision surrounding a stormwater pond.",
  },
  // 1200x630 crop for LinkedIn and Open Graph link previews, generated by
  // scripts/generate-brookside-social-preview.mjs (npm run media:generate).
  socialPreview: {
    src: "/images/civil-engineer/brookside-social-preview.webp",
    width: 1200,
    height: 630,
    alt: "Conceptual aerial visualization of the synthetic Brookside Meadows residential subdivision surrounding a stormwater pond.",
  },
  // Standing synthetic disclosure shown wherever the visual appears.
  disclosure:
    "Synthetic case-study visualization. Not a real project, survey, approved design, or constructed development.",
  // Screen-reader disclosure for the projects card. The projects workspace
  // bans final-decision vocabulary outright (including inside negative
  // statements), so this variant carries the same meaning without it.
  cardDisclosure:
    "Synthetic Brookside Meadows case-study visualization. Not a real project, survey, or constructed development.",
  // Proof-of-concept caption. It must keep the visual distinct from the
  // downloadable DXF: the image was not generated from the DXF and the DXF
  // was not generated from the image.
  proofCaption:
    "This visualization communicates the fictional Brookside Meadows project context. The downloadable DXF is a separately generated test drawing used to exercise the real upload and parsing pipeline.",
  // Documented ceiling for the generated social preview file size, enforced
  // by scripts/verify-brookside-media.mjs.
  socialPreviewMaxBytes: 350 * 1024,
} as const;

export type BrooksideMedia = typeof brooksideMedia;
