import Link from "next/link";
import { notFound } from "next/navigation";

import PageHeader from "@/components/PageHeader";
import SectionCard from "@/components/SectionCard";
import BoundaryNote from "@/components/BoundaryNote";
import EmptyState from "@/components/EmptyState";
import StatusChip, { humanizeStatus } from "@/components/StatusChip";
import { getProjectDetail, getSheetViewerContext } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function PlanSheetDetailPage(
  props: {
    params: Promise<{ projectId: string; sheetId: string }>;
  }
) {
  const params = await props.params;
  const project = await getProjectDetail(params.projectId);
  if (!project) {
    notFound();
  }
  const base = `/projects/${project.projectId}`;
  const context = await getSheetViewerContext(params.sheetId);

  return (
    <div>
      <PageHeader
        eyebrow={project.projectName}
        title={
          context
            ? `${context.sheet.sheetNumber} ${context.sheet.sheetTitle}`.trim()
            : "Plan sheet"
        }
        description="Review-support metadata and references for a plan sheet. This view shows recorded sheet metadata, hotspots, CAD metadata, and plan references. It does not render a CAD drawing and does not verify or validate the sheet."
      />

      <div className="mx-auto max-w-5xl space-y-6 px-4 py-10 sm:px-6 lg:px-8">
        <div className="flex flex-wrap gap-2">
          <Link href={`${base}/plan-consistency`} className="nav-link">
            Back to plan consistency
          </Link>
          <Link href={base} className="nav-link">
            Project overview
          </Link>
        </div>

        {context === null ? (
          <EmptyState
            title="Sheet metadata is unavailable"
            description="This plan sheet could not be loaded. Start the backend API, or the sheet may not exist for this project. This is a connection or lookup state, not a finding about the sheet."
          />
        ) : (
          <>
            <BoundaryNote note={context.previewNote} />

            <SectionCard title="Sheet metadata">
              <dl className="grid gap-x-6 gap-y-3 sm:grid-cols-2">
                {(
                  [
                    ["Sheet number", context.sheet.sheetNumber],
                    ["Title", context.sheet.sheetTitle],
                    ["Discipline", context.sheet.discipline],
                    ["Revision", context.sheet.revision],
                    ["Revision date", context.sheet.revisionDate ?? "n/a"],
                    ["Status", humanizeStatus(context.sheet.status)],
                    ["File name", context.sheet.fileName ?? "n/a"],
                    ["Purpose", context.sheet.sheetPurpose],
                  ] as [string, string][]
                ).map(([label, value]) => (
                  <div
                    key={label}
                    className="flex justify-between gap-4 border-b border-slate-100 pb-2"
                  >
                    <dt className="text-sm font-semibold text-slate-500">
                      {label}
                    </dt>
                    <dd className="text-sm text-slate-800">{value}</dd>
                  </div>
                ))}
              </dl>
              <p className="mt-3 text-xs text-slate-500">
                No drawing preview is rendered here. Sheet previews are not
                generated by this system.
              </p>
            </SectionCard>

            <SectionCard
              title={`Hotspots (${context.hotspots.length})`}
              description="Recorded review-support hotspots on this sheet. Each requires reviewer confirmation."
            >
              {context.hotspots.length === 0 ? (
                <p className="text-sm text-slate-500">
                  No hotspots recorded for this sheet.
                </p>
              ) : (
                <ul className="space-y-2">
                  {context.hotspots.map((h) => (
                    <li key={h.hotspotId} className="text-sm">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="font-semibold text-slate-800">
                          {h.label}
                        </span>
                        <StatusChip label={humanizeStatus(h.hotspotType)} />
                      </div>
                      {h.description ? (
                        <p className="text-slate-600">{h.description}</p>
                      ) : null}
                    </li>
                  ))}
                </ul>
              )}
            </SectionCard>

            <SectionCard title={`CAD metadata (${context.cadMetadata.length})`}>
              {context.cadMetadata.length === 0 ? (
                <p className="text-sm text-slate-500">
                  No CAD metadata recorded for this sheet.{" "}
                  <Link
                    href={`${base}/cad`}
                    className="text-water-700 hover:underline"
                  >
                    Open CAD intake
                  </Link>
                  .
                </p>
              ) : (
                <ul className="space-y-1 text-sm text-slate-700">
                  {context.cadMetadata.map((m) => (
                    <li key={m.cadMetadataId}>
                      {m.entityLabel} ({humanizeStatus(m.entityType)})
                    </li>
                  ))}
                </ul>
              )}
            </SectionCard>

            <SectionCard
              title={`Plan references (${context.planReferences.length})`}
            >
              {context.planReferences.length === 0 ? (
                <p className="text-sm text-slate-500">
                  No plan references recorded for this sheet.
                </p>
              ) : (
                <ul className="space-y-1 text-sm text-slate-700">
                  {context.planReferences.map((r) => (
                    <li key={r.planReferenceId}>
                      {r.referenceLabel}{" "}
                      <StatusChip
                        label={humanizeStatus(r.consistencyStatus)}
                      />
                    </li>
                  ))}
                </ul>
              )}
            </SectionCard>
          </>
        )}
      </div>
    </div>
  );
}
