"""Initial schema reflecting the current SQLAlchemy models.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-28

This initial migration creates the full current schema from the application's
SQLAlchemy metadata (every model registered on Base.metadata), so it stays in
sync with the models that local development previously created with
create_all. That includes all Phase 2 through Phase 14 review entities, the
production-foundation organization/user/membership/project-access tables, the
CAD intake and traceability tables, and the pilot request table with its
operator pipeline fields (status, internal_notes, last_contacted_at).

Adopting Alembic this way lets an existing create_all database be stamped at this
revision without recreating tables. Future schema changes are added as new
autogenerated migrations on top of this one; see docs/DEPLOYMENT.md.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.db.database import Base

# Import the models module so all tables register on Base.metadata.
from app.db import models  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create every table in the current model metadata."""

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Drop every table in the current model metadata."""

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
