import type { KnowledgeEntry } from "./types";

// Curated, allowlisted knowledge catalog for the Civil Engineer AI Guide.
// Every entry describes public project information only: no secrets, no
// tenant data, no environment values. Source paths are validated by
// scripts/check-guide-knowledge.mjs; a path that stops existing fails CI, so
// the catalog cannot silently go stale. Objective repository facts
// (dependency versions, route lists) come from the generated facts file, not
// from prose in this catalog.

export const KNOWLEDGE: KnowledgeEntry[] = [
  {
    id: "product-purpose",
    title: "What Civil Engineer AI is",
    topic: "product",
    shortAnswer:
      "Civil Engineer AI is a reviewer-controlled, evidence-first stormwater review-support platform. It organizes project documents, plan references, review findings, applicant responses, and revision history for municipal plan reviewers. It supports the review; a licensed engineer makes every decision.",
    detail: [
      "The product models plan review as evidence work: documents are indexed to the page level, findings cite the exact page that supports them, checklist items track evidence status, applicant responses are recorded across resubmittal rounds, and a reviewer-controlled package assembles the handoff.",
    ],
    limitation:
      "It never approves plans, certifies compliance, or replaces a licensed Professional Engineer.",
    keyPhrases: ["what is civil engineer ai", "what is this project", "what does this app do", "purpose of this project", "product overview"],
    aliases: ["overview", "about", "purpose", "portfolio project"],
    entities: ["civil engineer ai"],
    links: [
      { href: "/guided-demo", label: "Start Guided Demo" },
      { href: "/start-here", label: "Technical Overview" },
    ],
    sources: ["README.md", "docs/PRODUCT_OVERVIEW.md"],
    realOrSeeded:
      "The product code paths are real; the public demonstration reviews the synthetic Brookside Meadows fixture.",
    related: ["reviewer-workflow", "brookside-meadows", "human-review-boundary"],
    priority: 2,
    safety: "public",
  },
  {
    id: "reviewer-workflow",
    title: "The six-stage reviewer workflow",
    topic: "workflow",
    shortAnswer:
      "The reviewer journey has six stages: project intake, document and DXF intake, evidence indexing and retrieval, checklist and finding review, applicant response tracking, and reviewer-controlled handoff. Each stage links into the Brookside Meadows workspace.",
    keyPhrases: ["how does the workflow work", "review workflow", "reviewer journey", "workflow stages", "what are the steps", "how it works"],
    aliases: ["process", "stages", "journey", "queue"],
    links: [
      { href: "/guided-demo", label: "Guided Demo" },
      { href: "/dashboard/queue", label: "Reviewer Queue" },
    ],
    sources: ["app/page.tsx", "lib/demoJourney.ts"],
    implementation: ["lib/demoJourney.ts", "app/guided-demo/page.tsx"],
    related: ["evidence-retrieval", "response-packages", "brookside-meadows"],
    safety: "public",
  },
  {
    id: "brookside-meadows",
    title: "Brookside Meadows, the synthetic case study",
    topic: "demo",
    shortAnswer:
      "Brookside Meadows is a fictional 47-lot residential subdivision in the fictional Town of Hartwell. It is the public demonstration fixture: a 38.5-acre site draining toward a wetland and stream corridor near Quarry Road, with ten intentionally planted review issues to exercise the workflow. It is not a real project, submission, or approval.",
    detail: [
      "The planted issues include a design storm discrepancy, missing infiltration testing, a groundwater separation concern, a missing downstream culvert discussion, unclear maintenance ownership, an erosion-control phasing mismatch, an undocumented sediment observation, an open pipe-material RFI, a Pond A versus Basin 1 naming inconsistency, and a missing revised sheet C-3.1.",
    ],
    keyPhrases: ["what is brookside meadows", "brookside demo", "planted issues", "synthetic case study", "town of hartwell", "47 lot subdivision"],
    aliases: ["brookside", "hartwell", "sample project", "fixture", "demo project"],
    entities: ["brookside meadows", "town of hartwell", "quarry road"],
    links: [
      { href: "/projects/proj_brookside_meadows", label: "Open Brookside Meadows" },
      { href: "/guided-demo", label: "Guided Demo" },
    ],
    sources: ["docs/BROOKSIDE_MEADOWS_PROJECT_STORY.md", "data/brookside.ts"],
    realOrSeeded:
      "Entirely synthetic and labeled as such everywhere it appears; nothing was extracted from a real municipal submission.",
    related: ["synthetic-data", "detention-basins", "real-vs-seeded"],
    priority: 2,
    safety: "public",
  },
  {
    id: "detention-basins",
    title: "Where detention basin information lives in the demo",
    topic: "demo",
    shortAnswer:
      "The Brookside Meadows fixture proposes a wet detention basin (labeled Pond A on the grading plan and Basin 1 in the report, a planted naming inconsistency) and an infiltration basin. Their descriptions live in the seeded project fixture and project story; checklist items and findings reference them as review-support records.",
    keyPhrases: ["where is detention basin information", "detention basin", "infiltration basin", "pond a", "basin 1", "stormwater facilities", "basin naming"],
    aliases: ["basin", "pond", "detention", "infiltration"],
    entities: ["pond a", "basin 1"],
    links: [
      { href: "/projects/proj_brookside_meadows", label: "Brookside Meadows" },
      { href: "/findings", label: "Findings (demo)" },
    ],
    sources: ["data/brookside.ts", "docs/BROOKSIDE_MEADOWS_PROJECT_STORY.md", "data/findings.ts"],
    limitation:
      "This is fixture data for demonstration. The guide cannot evaluate whether any basin is adequately sized; that is an engineering decision for a licensed reviewer.",
    realOrSeeded: "Seeded fixture data, clearly labeled as synthetic.",
    related: ["brookside-meadows", "findings"],
    safety: "public",
  },
  {
    id: "synthetic-data",
    title: "Synthetic data disclosure",
    topic: "demo",
    shortAnswer:
      "All public demo records are seeded, synthetic review-support data. Every demo surface renders a data-source notice stating whether records came from the connected backend seed or the repository fixture snapshot. Nothing implies a real municipal submission or approval.",
    keyPhrases: ["is this demo data", "is this real data", "seeded data", "synthetic data", "fake data", "where does the data come from"],
    aliases: ["disclosure", "data source", "seed"],
    links: [{ href: "/start-here", label: "Technical Overview" }],
    sources: ["components/DataSourceNotice.tsx", "components/DemoDataBadge.tsx", "docs/real-vs-mocked.md"],
    related: ["real-vs-seeded", "brookside-meadows"],
    safety: "public",
  },
  {
    id: "real-vs-seeded",
    title: "What is real versus seeded",
    topic: "architecture",
    shortAnswer:
      "Implemented and real: the FastAPI backend, authentication and per-project access control, document storage, PDF page indexing, DXF metadata parsing, evidence retrieval, response packages, and the audit trail. Seeded: the Brookside Meadows case study content. Public demo routes intentionally render labeled fixture data; authenticated routes never substitute demo data after a failure, they render explicit error states instead.",
    keyPhrases: ["what is real and what is seeded", "real vs seeded", "real versus mocked", "is the backend real", "which parts are real"],
    aliases: ["mocked", "simulated", "implemented"],
    links: [{ href: "/start-here", label: "Technical Overview" }],
    sources: ["docs/real-vs-mocked.md", "docs/adr/0002-data-source-boundaries.md"],
    tests: ["app/api/__tests__/backendProxy.test.ts", "lib/api/__tests__/api.test.ts"],
    related: ["data-source-boundaries", "synthetic-data"],
    priority: 1,
    safety: "public",
  },
  {
    id: "data-source-boundaries",
    title: "Data-source boundaries and failure states",
    topic: "architecture",
    shortAnswer:
      "The typed API client returns an explicit result for every request: success carries the data and its source, and failures carry a category (sign-in required, forbidden, missing, validation, conflict, rate limited, timeout, backend unavailable, invalid response) plus a correlation ID. Authenticated surfaces render those states directly and never fall back to seeded data.",
    keyPhrases: ["what happens when the backend is down", "backend unavailable", "error handling", "failure states", "does it fall back to demo data", "silent fallback"],
    aliases: ["apiresult", "error states", "fallback"],
    sources: ["lib/api/client.ts", "components/RequestFailureCard.tsx", "docs/adr/0002-data-source-boundaries.md"],
    realOrSeeded:
      "Only the public Brookside demo surfaces may render the repository fixture snapshot, and they disclose it visibly when they do.",
    related: ["real-vs-seeded", "bff-proxy"],
    priority: 1,
    safety: "public",
  },
  {
    id: "frontend-architecture",
    title: "Frontend architecture",
    topic: "architecture",
    shortAnswer:
      "The frontend is Next.js App Router with TypeScript and Tailwind CSS. API modules in lib/api return typed results, wire types are generated from the FastAPI OpenAPI schema, and reusable state components cover loading, empty, and failure states. The production build runs in CI.",
    keyPhrases: ["frontend architecture", "what frontend framework", "next js", "react", "typescript", "tailwind", "tech stack", "built with"],
    aliases: ["stack", "frontend", "client"],
    links: [{ href: "/start-here", label: "Technical Overview" }],
    sources: ["docs/ARCHITECTURE.md", "package.json", "lib/api/client.ts"],
    related: ["backend-architecture", "openapi-contracts", "testing"],
    safety: "public",
  },
  {
    id: "backend-architecture",
    title: "Backend architecture",
    topic: "architecture",
    shortAnswer:
      "The backend is FastAPI with Pydantic schemas, SQLAlchemy models, and Alembic migrations. SQLite serves local development and tests; PostgreSQL is the production database. Services implement the review-support domains: documents, PDF evidence, CAD intake, checklists, findings, review cycles, response packages, workflow, audit, and billing scaffolding.",
    keyPhrases: ["backend architecture", "fastapi", "database", "sqlalchemy", "alembic", "postgresql", "python backend"],
    aliases: ["backend", "server", "api design"],
    sources: ["backend/app/main.py", "docs/ARCHITECTURE.md", "docs/adr/0005-backend-domain-decomposition.md"],
    related: ["frontend-architecture", "tenant-isolation", "audit-trail"],
    safety: "public",
  },
  {
    id: "authentication",
    title: "Authentication and sessions",
    topic: "security",
    shortAnswer:
      "Authentication is local accounts with PBKDF2 password hashing and signed access tokens. The browser never holds the token: sign-in stores it in an HttpOnly cookie whose lifetime comes from the backend's stated token expiry, and a same-origin proxy attaches it server-side. Session truth comes from a validated status endpoint, and an invalid session clears its cookies.",
    keyPhrases: ["how does authentication work", "how do sessions work", "login flow", "signin", "cookies", "httponly", "token storage", "session lifetime"],
    aliases: ["authentication", "session", "account"],
    links: [{ href: "/login", label: "Sign in" }],
    sources: ["docs/adr/0003-secure-session-architecture.md", "lib/server/session.ts", "app/api/session/login/route.ts", "backend/app/services/auth_service.py"],
    tests: ["app/api/__tests__/sessionRoutes.test.ts", "lib/server/__tests__/session.test.ts"],
    related: ["csrf-protection", "bff-proxy", "tenant-isolation"],
    priority: 1,
    safety: "public",
  },
  {
    id: "csrf-protection",
    title: "CSRF protection",
    topic: "security",
    shortAnswer:
      "Every cookie-authenticated mutating request must pass two independent checks: when an Origin header is present it must match the trusted application origin exactly, and the request must carry a custom header that a cross-site attacker cannot set without a CORS preflight the browser refuses. Cross-origin mutations receive an explicit 403.",
    keyPhrases: ["csrf", "cross site request forgery", "origin validation", "csrf header", "how are mutations protected"],
    aliases: ["csrf protection", "origin check"],
    sources: ["lib/server/session.ts", "docs/security/BFF_PROXY_THREAT_MODEL.md"],
    tests: ["lib/server/__tests__/session.test.ts", "app/api/__tests__/backendProxy.test.ts"],
    related: ["authentication", "bff-proxy"],
    safety: "public",
  },
  {
    id: "bff-proxy",
    title: "The backend-for-frontend proxy",
    topic: "security",
    shortAnswer:
      "All authenticated browser requests go through a same-origin proxy that forwards only validated backend API paths to the configured FastAPI origin. It enforces route-class body limits and upstream timeouts, streams uploads instead of buffering them, allowlists request and response headers, attaches the token from the HttpOnly cookie server-side, clears invalid sessions on 401, and stamps every request with a correlation ID.",
    keyPhrases: ["bff", "proxy", "backend for frontend", "how do api calls reach the backend", "upload limits", "timeouts", "open proxy"],
    aliases: ["gateway", "api proxy"],
    sources: ["app/api/backend/[...path]/route.ts", "docs/security/BFF_PROXY_THREAT_MODEL.md"],
    tests: ["app/api/__tests__/backendProxy.test.ts"],
    related: ["csrf-protection", "authentication", "security-limitations"],
    priority: 1,
    safety: "public",
  },
  {
    id: "tenant-isolation",
    title: "Tenant isolation and access control",
    topic: "security",
    shortAnswer:
      "Organizations, memberships, roles, and per-project access grants gate every project-owned API route in FastAPI. The Brookside demo project is intentionally public; every other project requires membership or an explicit grant, and unauthorized access returns an explicit 403 with no data and no fixture substitution.",
    keyPhrases: ["tenant isolation", "access control", "permissions", "roles", "who can see a project", "organization access"],
    aliases: ["authorization", "multi tenant", "guards"],
    sources: ["backend/app/services/access_control_service.py", "docs/TENANT_ISOLATION_AUDIT.md", "docs/AUTHENTICATION_AND_ACCESS_CONTROL.md"],
    related: ["authentication", "audit-trail"],
    safety: "public",
  },
  {
    id: "documents",
    title: "Documents and storage",
    topic: "features",
    shortAnswer:
      "Documents are registered or uploaded per project, stored through a provider abstraction (local disk for development, S3-compatible object storage for deployment), and tracked with intake status. Uploads are size-limited and extension-checked; storage credentials never reach the browser.",
    keyPhrases: ["how are documents stored", "document upload", "file storage", "object storage", "s3", "document intake"],
    aliases: ["files", "uploads", "storage"],
    links: [{ href: "/documents", label: "Documents (demo)" }],
    sources: ["backend/app/services/document_service.py", "backend/app/services/storage/storage_service.py", "docs/STORAGE_PROVIDER_ABSTRACTION.md"],
    related: ["pdf-indexing", "dxf-intake"],
    safety: "public",
  },
  {
    id: "pdf-indexing",
    title: "PDF page indexing and evidence citations",
    topic: "features",
    shortAnswer:
      "Digital PDFs are indexed page by page with pypdf: each page's embedded text becomes a searchable record, and findings cite the exact page and excerpt that support them. There is no OCR; scanned documents without a text layer are reported as extraction-unavailable rather than silently skipped.",
    keyPhrases: ["pdf indexing", "how are pdfs processed", "page level citations", "evidence citations", "pypdf", "text extraction"],
    aliases: ["pdf", "citations", "page index"],
    links: [{ href: "/projects/proj_brookside_meadows/evidence-search", label: "Evidence Search" }],
    sources: ["backend/app/services/pdf_indexing_service.py", "docs/PDF_PAGE_INDEXING_AND_EVIDENCE_CITATIONS.md"],
    related: ["evidence-retrieval", "documents"],
    safety: "public",
  },
  {
    id: "dxf-intake",
    title: "DXF and CAD intake",
    topic: "features",
    shortAnswer:
      "CAD intake parses DXF metadata deterministically with the ezdxf library: layers, blocks, text, and entity summaries become review-support records, and reference candidates can be compared against plan sheets. DXF is the only supported CAD format; DWG parsing, Autodesk integration, and geometry validation are intentionally out of scope.",
    keyPhrases: ["dxf", "cad intake", "cad parsing", "ezdxf", "dwg", "autodesk", "cad files"],
    aliases: ["cad", "drawings"],
    links: [{ href: "/cad-intake", label: "CAD Intake (demo)" }],
    sources: ["backend/app/services/cad_intake_service.py", "docs/PHASE_11_CAD_INTAKE_DXF_PARSING.md"],
    limitation: "It never verifies CAD drawings or validates final design geometry.",
    related: ["documents", "known-limitations"],
    safety: "public",
  },
  {
    id: "evidence-retrieval",
    title: "Evidence retrieval",
    topic: "features",
    shortAnswer:
      "Evidence retrieval is deterministic ranked search over indexed page text: no live AI calls and no external vector service. Results are candidates that require reviewer confirmation, and each cites its source page so the reviewer can verify it in context.",
    keyPhrases: ["evidence retrieval", "how does search work", "evidence search", "retrieval ranking", "vector search"],
    aliases: ["retrieval", "search", "evidence"],
    links: [{ href: "/projects/proj_brookside_meadows/evidence-search", label: "Evidence Search" }],
    sources: ["backend/app/services/evidence_retrieval_service.py", "backend/app/services/retrieval_service.py", "docs/API_EVIDENCE_RETRIEVAL.md"],
    related: ["pdf-indexing", "findings", "ai-behavior"],
    safety: "public",
  },
  {
    id: "findings",
    title: "Findings and plan consistency",
    topic: "features",
    shortAnswer:
      "Findings are review-support records: each one names a potential issue, cites its evidence, and carries a needs-human-review status. Nothing in the system marks a finding as a final determination; reviewer actions and dispositions are recorded with attribution in the audit trail.",
    keyPhrases: ["findings", "plan consistency", "review issues", "how are findings created", "finding definitions", "which file defines findings"],
    aliases: ["issues", "concerns", "flags"],
    links: [{ href: "/findings", label: "Findings (demo)" }],
    sources: ["backend/app/services/finding_service.py", "backend/app/services/plan_consistency_service.py", "data/findings.ts"],
    related: ["checklists", "evidence-retrieval", "human-review-boundary"],
    safety: "public",
  },
  {
    id: "checklists",
    title: "Checklists and rule packs",
    topic: "features",
    shortAnswer:
      "Reusable stormwater rule packs seed project checklists; each checklist item tracks its expected evidence and an evidence status such as supported, missing, conflicting, or unclear. The checklist drives what gets examined, not a free-form prompt.",
    keyPhrases: ["checklists", "rule packs", "checklist items", "stormwater checklist", "expected evidence"],
    aliases: ["rules", "requirements"],
    links: [{ href: "/checklist", label: "Checklist (demo)" }],
    sources: ["backend/app/services/checklist_review_service.py", "docs/CHECKLIST_RULE_PACK_FOUNDATION.md"],
    related: ["findings", "evidence-retrieval"],
    safety: "public",
  },
  {
    id: "response-packages",
    title: "Applicant responses, resubmittals, and packages",
    topic: "features",
    shortAnswer:
      "Applicant responses are tracked in a response matrix against the findings that prompted them, resubmittal rounds carry items forward across review cycles, and reviewer-controlled response packages assemble the communication record for handoff. Package issuance records a reviewer action, never an approval.",
    keyPhrases: ["response packages", "applicant responses", "resubmittals", "response matrix", "review cycles", "handoff package", "review packet"],
    aliases: ["responses", "packages", "handoff", "packets"],
    links: [
      { href: "/response-package", label: "Response Package (demo)" },
      { href: "/review-packet", label: "Review Packet (demo)" },
    ],
    sources: ["backend/app/services/response_package_service.py", "backend/app/services/review_cycle_service.py", "docs/API_RESPONSE_PACKAGES.md"],
    related: ["reviewer-workflow", "audit-trail"],
    safety: "public",
  },
  {
    id: "audit-trail",
    title: "The audit trail",
    topic: "features",
    shortAnswer:
      "Reviewer actions, accesses, and workflow transitions write durable audit events with actor attribution, so a finding's history can be reconstructed end to end. The public demo shows seeded events; authenticated project work writes real ones.",
    keyPhrases: ["audit trail", "audit events", "history", "who did what", "attribution"],
    aliases: ["audit", "log", "events"],
    links: [{ href: "/audit", label: "Audit (demo)" }],
    sources: ["backend/app/services/audit_service.py", "data/auditEvents.ts"],
    realOrSeeded: "Demo surface shows seeded events; authenticated actions write real audit records.",
    related: ["tenant-isolation", "response-packages"],
    safety: "public",
  },
  {
    id: "testing",
    title: "Testing and release gates",
    topic: "engineering",
    shortAnswer:
      "CI runs backend pytest with a 90 percent coverage floor, migration and import checks, frontend typecheck, lint, unit tests, a content integrity gate for attribution and em dash violations, a production dependency audit, the production build, and an API contract freshness check. Security-sensitive modules (the proxy, sessions, CSRF) have dedicated suites.",
    keyPhrases: ["testing", "test suites", "ci", "release gates", "coverage", "what tests exist", "compliance wording tests", "safety wording tests"],
    aliases: ["tests", "quality gates", "pipeline"],
    sources: [".github/workflows/ci.yml", "backend/app/core/safety.py", "scripts/check-content-integrity.mjs"],
    tests: ["app/api/__tests__/backendProxy.test.ts", "app/api/__tests__/sessionRoutes.test.ts"],
    related: ["ci-release", "professional-wording"],
    safety: "public",
  },
  {
    id: "ci-release",
    title: "CI and deployment",
    topic: "engineering",
    shortAnswer:
      "GitHub Actions runs the backend, frontend, and contract jobs on every push. Deployment targets Railway as two services (Next.js frontend and FastAPI backend) with health and readiness endpoints, environment validation that refuses unsafe production defaults, and diagnostics that drive the deployment-status page from real checks rather than a static badge.",
    keyPhrases: ["deployment", "railway", "ci pipeline", "github actions", "health check", "readiness", "deployment status"],
    aliases: ["deploy", "hosting", "infrastructure"],
    links: [{ href: "/deployment-status", label: "Deployment Status" }],
    sources: [".github/workflows/ci.yml", "docs/RAILWAY_DEPLOYMENT_GUIDE.md", "backend/app/services/environment_validation_service.py"],
    related: ["testing", "security-limitations"],
    safety: "public",
  },
  {
    id: "ai-behavior",
    title: "AI provider behavior",
    topic: "ai",
    shortAnswer:
      "Live AI calls are disabled by default. The public demo runs deterministically on a mock provider with no API key. Any optional live provider must be explicitly configured, is evidence-bounded and citation-required, and its output is validated so it can never issue an engineering decision. This guide itself is deterministic local retrieval, not a language model.",
    keyPhrases: ["does this use ai", "which ai model", "openai", "anthropic", "llm", "is the ai real", "mock provider", "live ai"],
    aliases: ["ai", "model", "provider"],
    sources: ["backend/app/ai/provider.py", "backend/app/ai/mock_provider.py", "backend/app/ai/validators.py"],
    tests: ["backend/tests"],
    related: ["guide-how-it-works", "human-review-boundary"],
    priority: 1,
    safety: "public",
  },
  {
    id: "guide-how-it-works",
    title: "How this guide works",
    topic: "ai",
    shortAnswer:
      "This guide is a deterministic local project expert: it searches an allowlisted knowledge catalog with token-aware ranking, synonym expansion, typo tolerance, and page-context boosts, then composes answers from curated entries with repository source references. Your questions never leave the browser: no outside inference API, no model download, no telemetry.",
    keyPhrases: ["how does this guide work", "are you an ai", "are you chatgpt", "is this a chatbot", "do you send my questions anywhere", "privacy of this chat"],
    aliases: ["guide", "assistant", "chat"],
    sources: ["lib/guide/search.ts", "lib/guide/knowledge.ts", "docs/civil-engineer-ai-guide.md"],
    limitation:
      "It only knows public project information from its catalog; it does not read the live repository or any tenant data at runtime.",
    related: ["ai-behavior", "known-limitations"],
    priority: 1,
    safety: "public",
  },
  {
    id: "human-review-boundary",
    title: "The human review boundary",
    topic: "safety",
    shortAnswer:
      "AI provides review support. You make the decisions. Every review is human. The system organizes evidence and drafts review-support findings; it never approves plans, certifies compliance, stamps drawings, declares a project safe, or replaces a licensed Professional Engineer, and there is no action named approve anywhere in the product.",
    keyPhrases: ["human review boundary", "professional boundary", "who makes decisions", "does it approve plans", "engineering decisions", "how does the app discuss permitting boundaries", "where is construction advice prohibited"],
    aliases: ["boundary", "limits", "responsibility"],
    sources: ["components/SafetyBoundaryBanner.tsx", "backend/app/core/safety.py", "CLAUDE.md"],
    tests: ["app/__tests__/finalQa.test.tsx"],
    related: ["professional-wording", "ai-behavior"],
    priority: 2,
    safety: "public",
  },
  {
    id: "professional-wording",
    title: "Enforced professional wording",
    topic: "safety",
    shortAnswer:
      "A safety vocabulary layer in the backend and content tests in the frontend prevent final-decision wording: statuses never say approved, certified, compliant, passed, or safe. Review-support language (needs human review, potential issue, consistency concern, ready for reviewer handoff) is enforced by tests, and a repository-wide content gate blocks prohibited wording in CI.",
    keyPhrases: ["forbidden words", "prohibited wording", "safety vocabulary", "does the repository contain compliance wording tests", "wording tests", "status labels"],
    aliases: ["vocabulary", "wording", "language rules"],
    sources: ["backend/app/core/safety.py", "scripts/check-content-integrity.mjs", "lib/dashboardLabels.ts"],
    related: ["human-review-boundary", "testing"],
    safety: "public",
  },
  {
    id: "security-limitations",
    title: "Security posture and limitations",
    topic: "security",
    shortAnswer:
      "The security model covers HttpOnly cookie sessions, CSRF gates, a hardened proxy with a written threat model, tenant guards, structured secrets handling, and production configuration validation. Known limitations are documented honestly: it is a pilot-posture system, not a hardened multi-tenant SaaS; there is no enterprise SSO, no email confirmation, and session renewal means signing in again after expiry.",
    keyPhrases: ["security limitations", "how secure is this", "security model", "threat model", "known security issues"],
    aliases: ["security", "hardening"],
    sources: ["docs/security/BFF_PROXY_THREAT_MODEL.md", "docs/SECURITY_AND_PROFESSIONAL_BOUNDARY.md", "docs/RELEASE_READINESS.md"],
    related: ["bff-proxy", "known-limitations"],
    safety: "public",
  },
  {
    id: "developer",
    title: "About the developer",
    topic: "developer",
    shortAnswer:
      "This project was developed by Michael Palmer as a software engineering portfolio focused on civil engineering review workflows, evidence-first systems, and human-in-the-loop AI support. He is a Computer Science student with professional experience across automotive technology, implementation, workflow design, and applied AI solutions.",
    keyPhrases: ["who built this", "who made this", "about the developer", "michael palmer", "linkedin", "github", "hire", "resume", "contact"],
    aliases: ["author", "creator", "developer"],
    links: [
      { href: "https://linkedin.com/in/mpalmer1234", label: "LinkedIn" },
      { href: "https://www.github.com/mpalmer79", label: "GitHub" },
      { href: "https://www.github.com/mpalmer79/civil-engineer", label: "Project Repository" },
    ],
    sources: ["README.md"],
    related: ["product-purpose", "repository-navigation"],
    safety: "public",
  },
  {
    id: "repository-navigation",
    title: "Navigating the repository",
    topic: "engineering",
    shortAnswer:
      "The frontend lives in app (routes), components, and lib (API modules, guide, server helpers); the backend lives in backend/app (api/v1 routes, services, db models, ai providers); documentation lives in docs with an index at docs/README.md, decision records under docs/adr, and the route map in docs/ROUTE_ARCHITECTURE.md.",
    keyPhrases: ["repository structure", "where is the code", "folder structure", "where are the docs", "adr", "architecture decision records", "route map"],
    aliases: ["structure", "layout", "navigation"],
    sources: ["docs/README.md", "docs/ROUTE_ARCHITECTURE.md", "README.md"],
    related: ["frontend-architecture", "backend-architecture"],
    safety: "public",
  },
  {
    id: "known-limitations",
    title: "Known limitations and roadmap",
    topic: "product",
    shortAnswer:
      "Intentionally out of scope: OCR, DWG parsing, Autodesk and GIS integration, computer vision, external vector search, enterprise SSO, and a full applicant portal. Live AI stays off by default. The roadmap tracks staged work such as deeper backend domain decomposition and browser test expansion, recorded in the transformation tracker and ADRs.",
    keyPhrases: ["known limitations", "what is out of scope", "roadmap", "future work", "what is missing", "current roadmap"],
    aliases: ["limitations", "scope", "todo"],
    sources: ["docs/real-vs-mocked.md", "docs/100_SCORE_TRANSFORMATION.md", "docs/ROADMAP.md"],
    related: ["real-vs-seeded", "security-limitations"],
    safety: "public",
  },
  {
    id: "for-civil-engineers",
    title: "Value for practicing reviewers",
    topic: "product",
    shortAnswer:
      "For a practicing reviewer the value is organization and traceability: documents indexed to the page level, findings linked to their evidence, checklist status at a glance, applicant responses recorded across rounds, and a handoff package that assembles the full picture. It reduces the clerical burden so the engineer's time goes to judgment.",
    keyPhrases: ["how can this help me as a civil engineer", "value for reviewers", "why would a reviewer use this", "save time", "municipal reviewer", "town engineer"],
    aliases: ["reviewer value", "benefits"],
    links: [
      { href: "/guided-demo", label: "Start Guided Demo" },
      { href: "/dashboard/queue", label: "Reviewer Queue" },
    ],
    sources: ["docs/PRODUCT_OVERVIEW.md", "docs/SAAS_POSITIONING.md"],
    limitation:
      "It is review support, not review automation: nothing here sizes a basin, checks a code section, or approves anything.",
    related: ["product-purpose", "reviewer-workflow"],
    safety: "public",
  },
];

export const KNOWLEDGE_BY_ID: Map<string, KnowledgeEntry> = new Map(
  KNOWLEDGE.map((entry) => [entry.id, entry]),
);
